// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvJC6Dt5zEO2zcAGp5B-irAaqE4EmincU',
    appId: '1:1095281113336:web:645fbc81323f543de6e30d',
    messagingSenderId: '1095281113336',
    projectId: 'smart-drop-off-box',
    authDomain: 'smart-drop-off-box.firebaseapp.com',
    databaseURL: 'https://smart-drop-off-box-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-drop-off-box.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAPkkHxoGA2zn2A-JV89O0hgsev5HHL74',
    appId: '1:1095281113336:android:604b7075e098e06ae6e30d',
    messagingSenderId: '1095281113336',
    projectId: 'smart-drop-off-box',
    databaseURL: 'https://smart-drop-off-box-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-drop-off-box.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUbRAYsknT42q-S2CNxUsHZ2U5uX_b_1k',
    appId: '1:1095281113336:ios:badcad7ed1184070e6e30d',
    messagingSenderId: '1095281113336',
    projectId: 'smart-drop-off-box',
    databaseURL: 'https://smart-drop-off-box-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-drop-off-box.firebasestorage.app',
    iosBundleId: 'com.example.smartDeliveryBoxMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUbRAYsknT42q-S2CNxUsHZ2U5uX_b_1k',
    appId: '1:1095281113336:ios:badcad7ed1184070e6e30d',
    messagingSenderId: '1095281113336',
    projectId: 'smart-drop-off-box',
    databaseURL: 'https://smart-drop-off-box-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-drop-off-box.firebasestorage.app',
    iosBundleId: 'com.example.smartDeliveryBoxMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvJC6Dt5zEO2zcAGp5B-irAaqE4EmincU',
    appId: '1:1095281113336:web:175e80e2a4bf5289e6e30d',
    messagingSenderId: '1095281113336',
    projectId: 'smart-drop-off-box',
    authDomain: 'smart-drop-off-box.firebaseapp.com',
    databaseURL: 'https://smart-drop-off-box-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-drop-off-box.firebasestorage.app',
  );
}
